const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function api(extra={}){const ctx={window:{},Date,URLSearchParams,AbortController,setTimeout,clearTimeout,...extra};vm.createContext(ctx);vm.runInContext(fs.readFileSync('app/climate-data.js','utf8'),ctx);return ctx.window.ClimateData;}
function record(wind=[359,1,180,90],speed=[2,2,.2,null]){return {year:2025,expected:4,data:{hourly_units:{wind_speed_10m:'m/s',temperature_2m:'°C',precipitation:'mm'},hourly:{time:['a','b','c','d'],wind_direction_10m:wind,wind_speed_10m:speed,temperature_2m:[0,10,null,20],relative_humidity_2m:[50,70,null,90],precipitation:[0,.1,null,2]}}};}
test('north-boundary directions remain north; calm is separate, missing wind is excluded',()=>{const r=api().summarize([record()]);assert.equal(r.sectors[0],2);assert.equal(r.sectors.reduce((a,b)=>a+b,0),2);assert.equal(r.calm,1);assert.equal(r.validWind,3);assert.equal(r.expected,4);assert.equal(r.meanTemperature,10);assert.equal(r.meanHumidity,70);assert.ok(Math.abs(r.wetPercent-200/3)<1e-10)});
test('late February respects leap years',()=>{assert.equal(api().range(2024,2,'late').hours,9*24);assert.equal(api().range(2025,2,'late').hours,8*24);assert.equal(api().range(2025,12,'late').end,'2025-12-31')});
test('missing wind and incompatible units fail rather than fabricate a summary',()=>{assert.throws(()=>api().summarize([record([null,null,null,null])]),/No valid/);const r=record();r.data.hourly_units.wind_speed_10m='km/h';assert.throws(()=>api().summarize([r]),/units/)});
test('requests exact seasonal windows, consistent ERA5, and last complete calendar years',async()=>{const urls=[];const a=api({fetch:async url=>{urls.push(url);return {ok:true,json:async()=>record().data}}});const r=await a.fetchPeriod({lat:0,lng:0,month:12,part:'late',years:3},new AbortController().signal);assert.equal(urls.length,3);const end=new Date().getUTCFullYear()-1;assert.equal(r.endYear,end);assert.equal(r.startYear,end-2);for(const u of urls){const q=new URL(u).searchParams;assert.equal(q.get('models'),'era5');assert.equal(q.get('wind_speed_unit'),'ms');assert.match(q.get('start_date'),/-12-21$/);assert.match(q.get('end_date'),/-12-31$/)}});
test('failed yearly request does not return a partial multi-year summary',async()=>{let n=0;const a=api({fetch:async()=>++n===1?{ok:true,json:async()=>record().data}:{ok:false,status:429}});await assert.rejects(a.fetchPeriod({lat:0,lng:0,month:12,part:'late',years:3},new AbortController().signal),/rate limit/);assert.equal(n,2)});
test('abort and invalid inputs make no archive requests',async()=>{let calls=0;const a=api({fetch:()=>{calls++;throw Error()}}),c=new AbortController();c.abort();await assert.rejects(a.fetchPeriod({lat:0,lng:0,month:12,part:'late',years:3},c.signal));await assert.rejects(a.fetchPeriod({lat:0,lng:0,month:13,part:'late',years:3}));assert.equal(calls,0)});
